name: 'Publish Conda package to Anaconda.org'
description: 'Build and Publish conda package to Anaconda'
author: 'Andrew Prokhorenkov, modified by Maxime Borry, modified by Jan Clemens'
branding:
  icon: 'package'  
  color: 'purple'
inputs: 
  subDir:
    description: 'Sub-directory with conda recipe'
    default: '.'
  AnacondaToken:
    description: 'Anaconda access Token'
  AnacondaUSER:
    description: 'Anaconda user'
  pyver:
    description: 'Python version build target'
    default: '3.9'
runs:
  using: 'docker'
  image: 'Dockerfile'
