name: 'Publish Conda package to Anaconda.org'
description: 'Build and Publish conda package to Anaconda'
author: 'Andrew Prokhorenkov, modified by Maxime Borry, modified by Jan Clemens'
branding:
  icon: 'package'  
  color: 'purple'
inputs: 
  recipe_directory:
    description: 'Sub-directory with conda recipe'
    default: '.'
  anaconda_token:
    description: 'Anaconda access Token'
  anaconda_user:
    description: 'Anaconda user'
  python_version:
    description: 'Python version build target'
    default: '3.9'
runs:
  using: 'docker'
  image: 'Dockerfile'
